version: '3.5'

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nodegreg
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: node_greg
    ports:
      - '3306:3306'
    volumes:
      - ./db/data.sql:/data/application/data.sql
    command: --init-file /data/application/data.sql
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    command: npm run dev